FROM ubuntu:16.04

MAINTAINER inocop


ARG APT_GET_MIRROR
ARG EMSCRIPTEN_VERSION="1.37.33"

RUN if [ "x${APT_GET_MIRROR}" != "x" ] ; then sed -i.bak -e "s%http://archive.ubuntu.com/ubuntu/%${APT_GET_MIRROR}%g" /etc/apt/sources.list ; fi \
&&  apt-get update \
&&  apt-get -y upgrade


# Install emscripten
RUN apt-get -y install build-essential \
                       cmake \
                       python2.7 \
                       nodejs \
                       default-jre \
                       git-core \
                       wget
RUN ln -s /usr/bin/python2.7 /usr/bin/python

RUN mkdir /root/myfastcomp \
&&  cd /root/myfastcomp \
&&  git clone --depth=1 -b ${EMSCRIPTEN_VERSION} --single-branch https://github.com/kripken/emscripten-fastcomp

RUN cd /root/myfastcomp/emscripten-fastcomp \
&&  git clone --depth=1 -b ${EMSCRIPTEN_VERSION} --single-branch https://github.com/kripken/emscripten-fastcomp-clang tools/clang

RUN cd /root/myfastcomp/emscripten-fastcomp \
&&  mkdir build \
&&  cd build \
&&  cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_TARGETS_TO_BUILD="X86;JSBackend" -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_TESTS=OFF \
&&  make -j2

WORKDIR /root
RUN git clone --depth=1 -b ${EMSCRIPTEN_VERSION} --single-branch https://github.com/kripken/emscripten.git

ENV PATH $PATH:/root/emscripten
ENV EMSCRIPTEN /root/emscripten
ENV LLVM /root/myfastcomp/emscripten-fastcomp/build/bin
ENV HOME /root
ENV DISPLAY :0
RUN echo "export DISPLAY=:0" >> /etc/profile

RUN emcc -v


ADD setup.sh /opt/setup.sh
ADD entry.sh /opt/entry.sh
RUN /opt/setup.sh

CMD /opt/entry.sh
