FROM ubuntu:16.04

MAINTAINER inocop


ARG APT_GET_MIRROR
ARG EMSCRIPTEN_VERSION="1.37.33"

RUN if [ "x${APT_GET_MIRROR}" != "x" ] ; then sed -i.bak -e "s%http://archive.ubuntu.com/ubuntu/%${APT_GET_MIRROR}%g" /etc/apt/sources.list ; fi \
&&  apt-get update \
&&  apt-get -y upgrade


# Install emscripten
RUN apt-get -y install build-essential \
                       cmake \
                       python2.7 \
                       nodejs \
                       default-jre \
                       git-core \
                       wget
RUN ln -s /usr/bin/python2.7 /usr/bin/python

WORKDIR /root
RUN wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz \
&&  tar -zxvf emsdk-portable.tar.gz

RUN cd /root/emsdk-portable \
&&  ./emsdk update \
&&  ./emsdk install -j2 sdk-${EMSCRIPTEN_VERSION}-64bit \
&&  ./emsdk activate sdk-${EMSCRIPTEN_VERSION}-64bit

RUN /bin/bash -c "source /root/emsdk-portable/emsdk_env.sh"
RUN ln -s $(find /root/emsdk-portable -name "emcc" | tail -n 1) /usr/local/bin/emcc

ENV HOME /root
ENV DISPLAY :0
RUN echo "export DISPLAY=:0" >> /etc/profile

RUN emcc -v


# Setting remote desktop
RUN apt-get -y install fluxbox \
                       x11vnc \
                       xvfb \
                       net-tools

RUN git clone https://github.com/novnc/noVNC.git /opt/novnc \
&&  git clone https://github.com/kanaka/websockify /opt/novnc/utils/websockify


# Install opengl
RUN apt-get -y install freeglut3-dev \
                       libglew-dev \
                       vim


# Setting ssh
RUN apt-get -y install openssh-server g++ gdb gdbserver \
&&  echo "root:root" | chpasswd \
&&  sed -e 's/^PermitRootLogin prohibit-password/PermitRootLogin yes/g' -i /etc/ssh/sshd_config


# Clean up
RUN apt-get autoclean \
&& apt-get autoremove \
&& rm -rf /var/lib/apt/lists/*


CMD /usr/bin/Xvfb :0 -screen 0 1024x768x24 \
&   /usr/bin/x11vnc -display :0 -forever \
&   /usr/bin/fluxbox -display :0 \
&   /opt/novnc/utils/launch.sh --vnc localhost:5900 --listen 6080 \
&   /etc/init.d/ssh start \
&&  tail -f /dev/null
