FROM ubuntu:16.04

MAINTAINER inocop


ARG APT_GET_MIRROR
ARG EMSCRIPTEN_VERSION="1.37.33"

RUN if [ "x${APT_GET_MIRROR}" != "x" ] ; then sed -i.bak -e "s%http://archive.ubuntu.com/ubuntu/%${APT_GET_MIRROR}%g" /etc/apt/sources.list ; fi \
&&  apt-get update \
&&  apt-get -y upgrade


# Install emscripten
RUN apt-get -y install build-essential \
                       cmake \
                       python2.7 \
                       nodejs \
                       default-jre \
                       git-core \
                       wget
RUN ln -s /usr/bin/python2.7 /usr/bin/python

WORKDIR /root
RUN wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz \
&&  tar -zxvf emsdk-portable.tar.gz

RUN cd /root/emsdk-portable \
&&  ./emsdk update \
&&  ./emsdk install -j2 --build=MinSizeRel sdk-${EMSCRIPTEN_VERSION}-64bit \
&&  ./emsdk activate sdk-${EMSCRIPTEN_VERSION}-64bit
RUN /bin/bash -c "source /root/emsdk-portable/emsdk_env.sh"


ENV PATH $PATH:/root/emsdk-portable/emscripten/${EMSCRIPTEN_VERSION}
ENV HOME /root
ENV DISPLAY :0
RUN echo "export DISPLAY=:0" >> /etc/profile

RUN emcc -v


ADD setup.sh /opt/setup.sh
ADD entry.sh /opt/entry.sh
RUN /opt/setup.sh

CMD /opt/entry.sh
