FROM ubuntu:16.04

MAINTAINER inocop


ARG APT_GET_MIRROR
ARG EMSCRIPTEN_VERSION="1.37.33"

RUN if [ "x${APT_GET_MIRROR}" != "x" ] ; then sed -i.bak -e "s%http://archive.ubuntu.com/ubuntu/%${APT_GET_MIRROR}%g" /etc/apt/sources.list ; fi \
&&  apt-get update \
&&  apt-get -y upgrade


# Install emscripten
RUN apt-get -y install build-essential \
                       cmake \
                       python2.7 \
                       nodejs \
                       default-jre \
                       git-core \
                       wget
RUN ln -s /usr/bin/python2.7 /usr/bin/python

RUN mkdir /root/myfastcomp \
&&  cd /root/myfastcomp \
&&  git clone --depth=1 -b ${EMSCRIPTEN_VERSION} --single-branch https://github.com/kripken/emscripten-fastcomp

RUN cd /root/myfastcomp/emscripten-fastcomp \
&&  git clone --depth=1 -b ${EMSCRIPTEN_VERSION} --single-branch https://github.com/kripken/emscripten-fastcomp-clang tools/clang

RUN cd /root/myfastcomp/emscripten-fastcomp \
&&  mkdir build \
&&  cd build \
&&  cmake .. -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86;JSBackend" -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_TESTS=OFF \
&&  make -j2

WORKDIR /root
RUN git clone --depth=1 -b ${EMSCRIPTEN_VERSION} --single-branch https://github.com/kripken/emscripten.git \
&&  ln -s /root/emscripten/emcc /usr/local/bin/emcc

ENV EMSCRIPTEN /root/emscripten
ENV LLVM /root/myfastcomp/emscripten-fastcomp/build/bin
ENV HOME /root
ENV DISPLAY :0
RUN echo "export DISPLAY=:0" >> /etc/profile


RUN emcc -v


# Setting remote desktop
RUN apt-get -y install fluxbox \
                       x11vnc \
                       xvfb \
                       net-tools

RUN git clone https://github.com/novnc/noVNC.git /opt/novnc \
&&  git clone https://github.com/kanaka/websockify /opt/novnc/utils/websockify


# Install opengl
RUN apt-get -y install freeglut3-dev \
                       libglew-dev \
                       vim


# Setting ssh
RUN apt-get -y install openssh-server g++ gdb gdbserver \
&&  echo "root:root" | chpasswd \
&&  sed -e 's/^PermitRootLogin prohibit-password/PermitRootLogin yes/g' -i /etc/ssh/sshd_config


# Clean up
RUN apt-get autoclean \
&& apt-get autoremove \
&& rm -rf /var/lib/apt/lists/*


CMD /usr/bin/Xvfb :0 -screen 0 1024x768x24 \
&   /usr/bin/x11vnc -display :0 -forever \
&   /usr/bin/fluxbox -display :0 \
&   /opt/novnc/utils/launch.sh --vnc localhost:5900 --listen 6080 \
&   /etc/init.d/ssh start \
&&  tail -f /dev/null
