FROM ubuntu:16.04

MAINTAINER inocop


ARG APT_GET_MIRROR

RUN if [ "x${APT_GET_MIRROR}" != "x" ] ; then sed -i.bak -e "s%http://archive.ubuntu.com/ubuntu/%${APT_GET_MIRROR}%g" /etc/apt/sources.list ; fi

# Install *gcc*(and related dependencies), cmake, Python, node.js, Java(optional, only needed for Closure Compiler minification), git, apache2
RUN apt-get update \
&&  apt-get -y install build-essential \
                       cmake \
                       python2.7 \
                       nodejs \
                       default-jre \
                       git-core \
                       apache2 \
                       wget \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python2.7 /usr/bin/python

WORKDIR /root
RUN wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz \
&&  tar -zxvf emsdk-portable.tar.gz

RUN cd /root/emsdk-portable \
&&  ./emsdk update \
&&  ./emsdk install -j1 latest \
&&  ./emsdk activate latest

RUN /bin/bash -c "source /root/emsdk-portable/emsdk_env.sh"
RUN ln -s $(find /root/emsdk-portable -name "emcc" | tail -n 1) /usr/local/bin/emcc
ENV HOME /root

# exec
CMD apachectl -D FOREGROUND
