FROM apiaryio/emcc:1.37

MAINTAINER inocop

RUN apt-get update \
&&  apt-get -y upgrade \
               cmake \
               git-core

ENV HOME /root
ENV DISPLAY :0
RUN echo "export DISPLAY=:0" >> /etc/profile

RUN echo 'alias ll="ls -l"' >> ~/.bashrc
RUN echo source ~/.bashrc


ADD setup.sh /opt/setup.sh
ADD entry.sh /opt/entry.sh
RUN /opt/setup.sh

CMD /opt/entry.sh
