FROM ubuntu:16.04

MAINTAINER inocop

RUN sed -i.bak -e "s%http://archive.ubuntu.com/ubuntu/%http://ftp.jaist.ac.jp/pub/Linux/ubuntu/%g" /etc/apt/sources.list

# Install *gcc*(and related dependencies), cmake, Python, node.js, Java(optional, only needed for Closure Compiler minification), git, apache2
RUN apt-get update \
&&  apt-get -y install build-essential \
                       cmake \
                       python2.7 \
                       nodejs \
                       default-jre \
                       git-core \
                       apache2 \
                       wget \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python2.7 /usr/bin/python

WORKDIR /tmp
RUN wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz \
&&  tar -zxvf emsdk-portable.tar.gz

WORKDIR /tmp/emsdk-portable

RUN ./emsdk update \
&&  ./emsdk install -j1 latest \
&&  ./emsdk activate latest \
&&  source ./emsdk_env.sh

# exec
CMD apachectl -D FOREGROUND
